spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mako2122
    url: jdbc:mysql://10.10.70.70:3306/study

jwt:
  secret: mako2122
  expiration: 36000


